### ISSUE TITLE
Why Joda time and not Java8 time API ?

### ISSUE THREAD

**Issue by guizmaii** [zalando/api-first-hand#21]
Hi,

Why do you use Joda time instead of the Java8 time API ?

**Comment by slavaschmidt** [comment]
Hi,

good point, actually. At the time we decided to use the JodaTime we were't sure if we'll support Java 7 or not. But as now the decision is not to do that, we probably could get rid of this external dependency.

Thanks!

**Comment by guizmaii** [comment]
Because of your work done in https://github.com/zalando/api-first-hand/pull/25, we can maybe close this issue ?

**Comment by slavaschmidt** [comment]
@guizmaii We are currently redesigning the whole marshalling for play and would like to test how it will work with java8 date-time classes. Then we'll close both issues. 

Does it make sense?

**Comment by guizmaii** [comment]
Yes ! Thanks :)

**Comment by slavaschmidt** [comment]
Fixed in v0.1.18
