### ISSUE TITLE
Recursive model definitions causes infinite loop

### ISSUE THREAD

**Issue by pocman** [zalando/api-first-hand#22]
Are you supporting Recursive models ?
It looks like this definition is causing an infinite loop : https://github.com/swagger-api/swagger-codegen/issues/728

**Comment by slavaschmidt** [comment]
The test data generators fail to compile in the case of circular dependency

**Comment by nmcb** [comment]
Hmmmm, bummer; can I help you with that ?

**Comment by slavaschmidt** [comment]
@nmcb thanks! Hope I already managed that, CI is currently running :)

**Comment by slavaschmidt** [comment]
Fixed in v0.1.18
