### ISSUE TITLE
create new release 0.2.0

### ISSUE THREAD

**Issue by domdorn** [zalando/api-first-hand#42]
I've seen that there are many improvements in the mustache templates in master.
In particular, the ability to add additional injects would be required by me. 

could you please release a new version and publish it to maven central ? 
That would be really great!

Thanks,
Dominik

**Comment by slavaschmidt** [comment]
We are looking into publishing the 0.2.0 as soon as possible, but unfortunately there are still lots of bugs there.

**Comment by LappleApple** [comment]
Hey @slavaschmidt, what's the status on this -- still open? :)

**Comment by slavaschmidt** [comment]
@LappleApple yes, the next version is not ready yet

**Comment by slavaschmidt** [comment]
Hey @LappleApple, @gipeshka, @sergey-novikov, with the enum issue solved I'm feeling that we could release the 0.2.0 version and update the activator template so that plugin users can use and test the new functionality. 

We would address open issues in 0.2.1 then. 

Do you think it is a good idea?

**Comment by s12v** [comment]
@slavaschmidt, yes 👍

**Comment by gipeshka** [comment]
👍

**Comment by s12v** [comment]
@slavaschmidt, @LappleApple, I can see 0.2.0 on bintray.com. Is it the latest master?
Could you please create a release on github, so we know the exact commit for 0.2.0?
