### ISSUE TITLE
Schema responses type should not have to start with capital letter

### ISSUE THREAD

**Issue by alexec** [zalando/api-first-hand#63]
You can have a response type (i.e. in you definition block) that has a lowercase first let, it produces code that will not compile. This is related to the case classes that are produced (which have title case). 

I'll update with more details shortly.

**Comment by slavaschmidt** [comment]
Hey @alexec, thank you very much for the report! I've tried to change type definitions in the `simple.petstore.api.yaml` from lower to uppercase and back and could not reproduce the issue.

It would be very helpful if you could provide small yet complete specification which we could use to drive our bugfix efforts.

**Comment by alexec** [comment]
Sorry - due to change in work, I'm afraid I won't have a chance to look at this. Feel free to close.
