### ISSUE TITLE
Easy question: Which of these exist vs. which of these are still in plans?

### ISSUE THREAD

**Issue by LappleApple** [zalando/api-first-hand#64]
Hi @slavaschmidt and @all maintainers:

The README says: "The status of this software is beta, an end-to-end functional release intended to demonstrate the possibility to generate following from a Swagger specification:

- Play route files
- Generators of random test data
 - Wrappers for Play route files to convert semantics from http-related to domain-related (controller_base)
 - Skeletons for the domain-driven controller implementation
- Model classes and validation rules
 - Unit tests for invalid and valid parameter sets
 -  Security extractors (if needed)
  -  Skeletons for custom deserializers (if needed)"

Which of these things exist in the current version? Which ones do not, and are highly desired?

**Comment by slavaschmidt** [comment]
Everything is there :)

**Comment by LappleApple** [comment]
Great, thank you!
