### ISSUE TITLE
What's Beta build-status: the plugin?

### ISSUE THREAD

**Issue by LappleApple** [zalando/api-first-hand#66]
It's not super-clear, so I wanted to check.

**Comment by LappleApple** [comment]
@slavaschmidt Hey, you probably know the answer best :)

**Comment by slavaschmidt** [comment]
@LappleApple Sorry, what do you mean with `Beta build-status`?

**Comment by LappleApple** [comment]
@slavaschmidt: This (https://github.com/zalando/api-first-hand/#build-status) says "the software is in beta status" ...

**Comment by slavaschmidt** [comment]
Yep, I just don't get the question. It's definitely not production ready, that's for sure. It might even be in alpha status again, as we didn't managed to iron out issues related to migration to play 2.5

**Comment by LappleApple** [comment]
@slavaschmidt was double-checking that you meant the plugin and not the template or something else
