### ISSUE TITLE
Is this doc still relevant?

### ISSUE THREAD

**Issue by LappleApple** [zalando/api-first-hand#68]
https://github.com/zalando/api-first-hand/blob/master/docs/REFERENCES.md

Asking because the main README has [this:](https://github.com/LappleApple/api-first-hand#specification-cross-references)

If not, we can delete it.

**Comment by slavaschmidt** [comment]
The `REFERENCES` is in-depth explanation how we work with json references in the plugin's source code. This is supposed to be useful for plugin developers as opposed to the plugin uses, for which is the section in the `README`

**Comment by LappleApple** [comment]
Thanks, @slavaschmidt! This sentence is a little confusing: "A $ref element of the specification is allowed to contain **a name of file** as its part." As its part of what, exactly? And "a name of file" means ... can we be a bit more specific?

**Comment by LappleApple** [comment]
Also this sentence: "It is also possible to reference a definition in one specification from another specification." [rewrite as?] => "You can reference a definition in one specification across other specifications."

**Comment by slavaschmidt** [comment]
👍

**Comment by slavaschmidt** [comment]
> This sentence is a little confusing: "A $ref element of the specification is allowed to contain a name of file as its part." As its part of what, exactly? And "a name of file" means ... can we be a bit more specific?

It basically means, you can use filename to reference part of another specification.

**Comment by LappleApple** [comment]
Does this make sense to you, @slavaschmidt?

>> You can use a filename to reference part of another specification with the `$ref` element. You can split a single specification into multiple files (as shown in [`cross_spec_references.yaml`](https://github.com/zalando/api-first-hand-activator/blob/master/conf/examples/cross_spec_references.yaml)). You can also reference a definition in one specification across other specifications.

**Comment by slavaschmidt** [comment]
Totally. For example one can create `domain_model.yaml` and then reference it from any other API specification

**Comment by LappleApple** [comment]
Awesome, thank you @slavaschmidt!
