### ISSUE TITLE
Activator Template contents: checking/updating

### ISSUE THREAD

**Issue by LappleApple** [zalando/api-first-hand#69]
Hey @slavaschmidt:

In this section, https://github.com/LappleApple/api-first-hand/blob/master/README.md#more-about-the-activator-template, I'm wondering ..

- _HTML tutorial (found in the tutorial folder)_ ... does this folder still exist in the template? I just went [here](https://www.lightbend.com/activator/template/api-first-hand) and downloaded "Template Bundle for "Api-First-Hand activator template." I can't find a tutorial version in the zip.
- _A template Swagger API definition called example.yaml, with a dummy implementation in the app folder_ : can you provide the name of the file in the app folder that includes the dummy implementation?

I'm also trying to get the language updated for the tutorial [here](https://www.lightbend.com/activator/template/api-first-hand); it still uses play-swagger :).

**Comment by slavaschmidt** [comment]
>HTML tutorial (found in the tutorial folder) ... does this folder still exist in the template? I just went here and downloaded "Template Bundle for "Api-First-Hand activator template." I can't find a tutorial version in the zip.

I guess this is referring to that tutorial: https://github.com/zalando-incubator/api-first-hand-service/blob/master/tutorial/index.html

> A template Swagger API definition called example.yaml, with a dummy implementation in the app folder : can you provide the name of the file in the app folder that includes the dummy implementation?

https://github.com/zalando-incubator/api-first-hand-service/blob/master/app/generated_controllers/example.yaml.scala

**Comment by LappleApple** [comment]
Thanks!
