### ISSUE TITLE
Move from Activator to Giter8

### ISSUE THREAD

**Issue by alexkops** [zalando/api-first-hand#84]
Lightbend has announced EOL for Activator at 24th of May (end of 2017 for the Activator server).
Instead of Activator templates they now support Giter8 via sbt, so the api-first-hand template should be migrated as well

http://developer.lightbend.com/blog/2017-03-17-how-to-migrate-activator-template/

**Comment by slavaschmidt** [comment]
More related to the https://github.com/zalando-incubator/api-first-hand-service

**Comment by alexkops** [comment]
Ok, created an issue there! 
https://github.com/zalando-incubator/api-first-hand-service/issues/12
